
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';
import { ConnectWallet } from '@thirdweb-dev/react';
import { useRouter } from 'next/router';
import NftData from '../components/common/nftData';
import { useMediaQuery } from 'react-responsive';
import MobileView from '../components/common/mobileView';
import dynamic from "next/dynamic";

function Home() {

  const router = useRouter();

  const isDesktopOrLaptop = useMediaQuery({
    query: '(min-width: 1224px)'
  })

  const { data, address, isLoading, error } = NftData();

  const purpleFrnId = 193;

  const [isPurpleFriendFound, setIsPurpleFriendFound] = useState(false);

  useEffect(() => {
    if (!address) {
      router.push('/login');
      return;
    }

    console.log(data);

    if (data) {
      const editionArray = data.map(item => item.metadata.edition);
      console.log('editionArray', editionArray);
      if (editionArray.includes(purpleFrnId)) {
        console.log('found');
        setIsPurpleFriendFound(true)
      } else {
        console.log('Not found');
        setIsPurpleFriendFound(false)

      }

    }

  }, [data, address]);

  useEffect(() => {
    // Get the elements
    // const menuOptionsDiv = document.querySelectorAll('.menu-options__item');

    // const mainBgsDiv = document.querySelector('.main-bg');
    // console.log(menuOptionsDiv);
    // const ai1Div = document.querySelector('.ai-1');

    // // Add event listener for mouseenter
    // // menuOptionsDiv.
    // [...menuOptionsDiv].map((item, i) => {
    //   // console.log(item.getAttribute('data-menu-item').slice(-1));
    //   const hoveredId = item.getAttribute('data-menu-item').slice(-1)
    //   item.addEventListener('mouseenter', (e) => {

    //     const aiDiv = document.querySelector(`.ai-${hoveredId}`);

    //     aiDiv.classList.add('item-hovered');

    //   })

    // })

    const mainBgsDiv = document.querySelector('.main-bg');
    const menuOptDiv = document.querySelectorAll('.menu-options__item');
    const menuOptImgs = document.querySelectorAll('.main-bg__asset-items img');
    const mainBgSky = document.querySelector('.main-bg__sky');
    const mainFrontSprites = document.querySelector('.front-spites');


    [...menuOptDiv].forEach((item, i) => {
      console.log(item);

      item.addEventListener('mouseenter', (e) => {
        console.log('triggered', item.getAttribute('data-menu-item').slice(-1));
        [...menuOptImgs][i].classList.add('item-hovered')
        item.classList.add('item-hovered')
        mainBgsDiv.classList.add('item-hovered')
        mainBgSky.classList.add('item-hovered')
        mainFrontSprites.classList.add('item-hovered')

      })


      item.addEventListener('mouseleave', (e) => {
        console.log('Left');
        [...menuOptImgs][i].classList.remove('item-hovered')
        item.classList.remove('item-hovered')
        mainBgsDiv.classList.remove('item-hovered')
        mainBgSky.classList.remove('item-hovered')
        mainFrontSprites.classList.remove('item-hovered')

      })

    });

    // [...menuOptImgs].forEach((item, i) => {
    //   console.log(item);
    //   item.classList.add('sss')
    // });


    // menuOptionsDiv.addEventListener('mouseenter', (e) => {
    //   ai1Div.classList.add('item-hovered');
    //   console.log(e.target.getAttribute('data-menu-item'));
    //   menuOptionsDiv.classList.add('item-hovered')
    //   mainBgsDiv.classList.add('item-hovered')
    // });

    // // Add event listener for mouseleave (optional: to remove the class when mouse leaves)
    // menuOptionsDiv.addEventListener('mouseleave', () => {
    //   ai1Div.classList.remove('item-hovered');
    //   menuOptionsDiv.classList.remove('item-hovered')
    //   mainBgsDiv.classList.remove('item-hovered')
    // });

  }, []);


  return (
    <div className={styles.container}>
      <Head>
        <title>Arkadia Map</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className='wallet-options'>
          <ConnectWallet />

        </div>
        {
          isDesktopOrLaptop && <div className='main-bg'>

            <div className='front-spites'>
              <img className='fs-sp-1' src="sky-bg-4.png" alt="island" />
              <div className='fs-absolute'>
                <img className='fs-blsp-1' src="bl-1.png" alt="island" />
                <img className='fs-blsp-2' src="bl-2.png" alt="island" />
                <img className='fs-blsp-3' src="bl-3.png" alt="island" />
              </div>
            </div>

            <div className='main-bg__img'>

              {/* <img src="island-main2.png" alt="island" /> */}
              <img src="main-island-up-2.png" alt="island" />
              {/* <img src="sky-bg-4.png" alt="island" /> */}

              <div className='main-bg__container'>
                <div className='main-bg__asset-items '>
                  <img className='ai-1' src="i1.png" alt="" />
                </div>
                <div className='main-bg__asset-items '>
                  <img className='ai-2' src="i2.png" alt="" />
                </div>
                <div className='main-bg__asset-items '>
                  <img className='ai-3' src="i3.png" alt="" />
                </div>
                <div className='main-bg__asset-items '>
                  <img className='ai-4' src="i4.png" alt="" />
                </div>
                {/* <div className='main-bg__asset-items '>
                  <img className='ai-5' src="i6.png" alt="" />
                </div> */}
                <div className='main-bg__asset-items '>
                  <img className='ai-6' src="i5.png" alt="" />
                </div>
                <div className='main-bg__asset-items '>
                  <img className='ai-7' src="i7.png" alt="" />
                </div>
                <div className='main-bg__asset-items '>
                  <img className='ai-7' src="i8.png" alt="" />
                </div>
                <div className='main-bg__asset-items '>
                  <img className='ai-7' src="i9.png" alt="" />
                </div>


              </div>
              {
                isPurpleFriendFound && <div className='main-bg__asset-items main-bg__asset-items--purle-friend'>
                  <img src="pupleFrndFrame.png" alt="" />
                </div>
              }
            </div>

            <div className='menu-options'>
              <div data-menu-item='dm-1' className='menu-options__item menu-options__item--i1'>
                <div className='menu-tip'>
                  <div className='menu-tip__info'>
                    <h4>Salon</h4>
                    <p>  Get enough strand of hair<br /> NFTs to mint your FREN</p>
                  </div>
                </div>
              </div>
              <div data-menu-item='dm-2' className='menu-options__item menu-options__item--i2'>
                <div className='menu-tip'>
                  <div className='menu-tip__info'>
                    <h4>Castle of Lore</h4>
                    <p>Learn about the history of Arkadia</p>
                  </div>
                </div>
              </div>
              <div data-menu-item='dm-3' className='menu-options__item menu-options__item--i3'>
                <div className='menu-tip'>
                  <div className='menu-tip__info'>
                    <h4>Ark</h4>
                    <p>This is some sample Text</p>
                  </div>
                </div>
              </div>
              <div data-menu-item='dm-4' className='menu-options__item menu-options__item--i4'>
                <div className='menu-tip'>
                  <div className='menu-tip__info'>
                    <h4>Honey</h4>
                    <p>This is honey</p>
                  </div>
                </div>
              </div>
              {/* <div data-menu-item='dm-5' className='menu-options__item menu-options__item--i5'>
                <div className='menu-tip'>
                  <div className='menu-tip__info'>
                    <h4>Bridge</h4>
                    <p>This is some sample Text</p>
                  </div>
                </div>
              </div> */}
              <div data-menu-item='dm-6' className='menu-options__item menu-options__item--i6'>
                <div className='menu-tip'>
                  <div className='menu-tip__info'>
                    <h4>Purple Trees</h4>
                    <p>This is some sample Text</p>
                  </div>
                </div>
              </div>

              <div data-menu-item='dm-7' className='menu-options__item menu-options__item--i7'>
                <div className='menu-tip'>
                  <div className='menu-tip__info'>
                    <h4>Fruit Market</h4>
                    <p>Trade your Purple Fruits</p>
                  </div>
                </div>
              </div>

              <div data-menu-item='dm-8' className='menu-options__item menu-options__item--i8'>
                <div className='menu-tip'>
                  <div className='menu-tip__info'>
                    <h4>Seed Deposit</h4>
                    <p>Mint Seeds Weekly</p>
                  </div>
                </div>
              </div>
              <div data-menu-item='dm-9' className='menu-options__item menu-options__item--i9'>
                <div className='menu-tip'>
                  <div className='menu-tip__info'>
                    <h4>Brdige</h4>
                    <p>This is some sample Text</p>
                  </div>
                </div>
              </div>
            </div>

            <div className='main-bg__sky'>
              <img className='mb-sk-1' src="sky-bg-1.png" alt="island" />
              <img className='mb-sk-2' src="sky-bg-2.png" alt="island" />
              <img className='mb-sk-3' src="sky-bg-3.png" alt="island" />


            </div>
          </div>
        }

        {
          !isDesktopOrLaptop && <MobileView />
        }


      </div>

    </div>
  )


}


export default dynamic(() => Promise.resolve(Home), { ssr: false })
