
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect } from 'react';

export default function Home() {



  useEffect(() => {
    // Get the elements
    // const menuOptionsDiv = document.querySelectorAll('.menu-options__item');

    // const mainBgsDiv = document.querySelector('.main-bg');
    // console.log(menuOptionsDiv);
    // const ai1Div = document.querySelector('.ai-1');

    // // Add event listener for mouseenter
    // // menuOptionsDiv.
    // [...menuOptionsDiv].map((item, i) => {
    //   // console.log(item.getAttribute('data-menu-item').slice(-1));
    //   const hoveredId = item.getAttribute('data-menu-item').slice(-1)
    //   item.addEventListener('mouseenter', (e) => {

    //     const aiDiv = document.querySelector(`.ai-${hoveredId}`);

    //     aiDiv.classList.add('item-hovered');

    //   })

    // })

    const mainBgsDiv = document.querySelector('.main-bg');
    const menuOptDiv = document.querySelectorAll('.menu-options__item');
    const menuOptImgs = document.querySelectorAll('.main-bg__asset-items img');
    const mainBgSky = document.querySelector('.main-bg__sky');
    const mainFrontSprites = document.querySelector('.front-spites');


    [...menuOptDiv].forEach((item, i) => {
      console.log(item);

      item.addEventListener('mouseenter', (e) => {
        console.log('triggered', item.getAttribute('data-menu-item').slice(-1));
        [...menuOptImgs][i].classList.add('item-hovered')
        item.classList.add('item-hovered')
        mainBgsDiv.classList.add('item-hovered')
        mainBgSky.classList.add('item-hovered')
        mainFrontSprites.classList.add('item-hovered')

      })


      item.addEventListener('mouseleave', (e) => {
        console.log('Left');
        [...menuOptImgs][i].classList.remove('item-hovered')
        item.classList.remove('item-hovered')
        mainBgsDiv.classList.remove('item-hovered')
        mainBgSky.classList.remove('item-hovered')
        mainFrontSprites.classList.remove('item-hovered')

      })

    });

    // [...menuOptImgs].forEach((item, i) => {
    //   console.log(item);
    //   item.classList.add('sss')
    // });


    // menuOptionsDiv.addEventListener('mouseenter', (e) => {
    //   ai1Div.classList.add('item-hovered');
    //   console.log(e.target.getAttribute('data-menu-item'));
    //   menuOptionsDiv.classList.add('item-hovered')
    //   mainBgsDiv.classList.add('item-hovered')
    // });

    // // Add event listener for mouseleave (optional: to remove the class when mouse leaves)
    // menuOptionsDiv.addEventListener('mouseleave', () => {
    //   ai1Div.classList.remove('item-hovered');
    //   menuOptionsDiv.classList.remove('item-hovered')
    //   mainBgsDiv.classList.remove('item-hovered')
    // });

  }, []);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className='main-bg'>

          <div className='front-spites'>
            <img src="sky-bg-4.png" alt="island" />
          </div>

          <div className='main-bg__img'>
            <img src="main-island.svg" alt="island" />
            {/* <img src="sky-bg-4.png" alt="island" /> */}

            <div className='main-bg__asset-items'>
              <img className='ai-1' src="i1.png" alt="" />
            </div>
            <div className='main-bg__asset-items'>
              <img className='ai-2' src="i2.png" alt="" />
            </div>
            <div className='main-bg__asset-items'>
              <img className='ai-3' src="i3.png" alt="" />
            </div>

          </div>

          <div className='menu-options'>
            <div data-menu-item='dm-1' className='menu-options__item menu-options__item--i1'>
              <div className='menu-tip'>
                <div className='menu-tip__info'>
                  <h4>Paragraph</h4>
                  <p>This is some sample Text</p>
                </div>
              </div>
            </div>
            <div data-menu-item='dm-2' className='menu-options__item menu-options__item--i2'>
              <div className='menu-tip'>
                <div className='menu-tip__info'>
                  <h4>Paragraph</h4>
                  <p>This is some sample Text</p>
                </div>
              </div>
            </div>

            <div data-menu-item='dm-3' className='menu-options__item menu-options__item--i3'>
              <div className='menu-tip'>
                <div className='menu-tip__info'>
                  <h4>Paragraph</h4>
                  <p>This is some sample Text</p>
                </div>
              </div>
            </div>

          </div>

          <div className='main-bg__sky'>
            <img className='mb-sk-1' src="sky-bg-1.png" alt="island" />
            <img className='mb-sk-2' src="sky-bg-2.png" alt="island" />
            <img className='mb-sk-3' src="sky-bg-3.png" alt="island" />
          </div>
        </div>

      </div>

    </div>
  )
}
